name: config service CI
on:
  push:
    branches:
      - main
  
jobs:
  sast:
    name: Security Analysis (Static Application Security Testing)
    uses: https://github.com/Rahul-Bristlecone/user-account-service.git/.github/workflows/sast.yaml@main
    with:
      target-environment: production
    secrets: inherit
  
  ci:
    name: Build and Test
    needs: sast
    uses: https://github.com/Rahul-Bristlecone/user-account-service.git/.github/workflows/reusable-ci.yaml@main
    with:
      service-name: config-service
      docker-repo: daemons
      target-environment: production
    secrets: inherit

  zap:
    name: OWASP ZAP Scan
    needs: ci
    uses: https://github.com/Rahul-Bristlecone/user-account-service.git/.github/workflows/zap.yaml@main
    with:
      target-url: https://marry-fifty-rocky.ngrok-free.dev
    secrets: inherit
